import { ToastContainer } from 'material-react-toastify'
import { NuqsAdapter } from 'nuqs/adapters/next'

import type { Metadata } from 'next'

import './globals.css'

import 'material-react-toastify/dist/ReactToastify.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <NuqsAdapter>
          <ToastContainer />
          {children}
        </NuqsAdapter>
      </body>
    </html>
  )
}
